# Generated by Django 5.0.7 on 2024-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='name_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
