# Generated by Django 5.0.7 on 2024-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appui', '0002_api_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
