# Generated by Django 5.0.7 on 2024-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appui', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_model',
            name='type_lang',
            field=models.CharField(choices=[('Markup', 'markup'), ('HTML', 'html'), ('XML', 'xml'), ('SVG', 'svg'), ('MathML', 'mathml'), ('CSS', 'css'), ('Clike', 'clike'), ('JavaScript', 'javascript'), ('ABAP', 'abap'), ('ActionScript', 'actionscript'), ('Ada', 'ada'), ('Apache Configuration', 'apacheconf'), ('APL', 'apl'), ('AppleScript', 'applescript'), ('Arduino', 'arduino'), ('ARM Assembly', 'armasm'), ('ASP.NET', 'aspnet'), ('AutoHotkey', 'autohotkey'), ('AutoIt', 'autoit'), ('Bash', 'bash'), ('Basic', 'basic'), ('Batch', 'batch'), ('Bison', 'bison'), ('Brainfuck', 'brainfuck'), ('C', 'c'), ('C#', 'csharp'), ('C++', 'cpp'), ('CoffeeScript', 'coffeescript'), ('Crystal', 'crystal'), ('D', 'd'), ('Dart', 'dart'), ('Diff', 'diff'), ('Django', 'django'), ('Docker', 'docker'), ('Eiffel', 'eiffel'), ('Elixir', 'elixir'), ('Elm', 'elm'), ('Erlang', 'erlang'), ('Flow', 'flow'), ('Fortran', 'fortran'), ('F#', 'fsharp'), ('Gherkin', 'gherkin'), ('Git', 'git'), ('GLSL', 'glsl'), ('Go', 'go'), ('GraphQL', 'graphql'), ('Groovy', 'groovy'), ('Haml', 'haml'), ('Handlebars', 'handlebars'), ('Haskell', 'haskell'), ('Haxe', 'haxe'), ('HTTP', 'http'), ('IDL', 'idl'), ('Java', 'java'), ('Jolie', 'jolie'), ('JSON', 'json'), ('Julia', 'julia'), ('Keyman', 'keyman'), ('Kotlin', 'kotlin'), ('LaTeX', 'latex'), ('Less', 'less'), ('Lisp', 'lisp'), ('LiveScript', 'livescript'), ('Lua', 'lua'), ('Makefile', 'makefile'), ('Markdown', 'markdown'), ('MATLAB', 'matlab'), ('MEL', 'mel'), ('Mizar', 'mizar'), ('Monkey', 'monkey'), ('N4JS', 'n4js'), ('Nasm', 'nasm'), ('NGINX', 'nginx'), ('Nim', 'nim'), ('Nix', 'nix'), ('Objective-C', 'objectivec'), ('OCaml', 'ocaml'), ('OpenCL', 'opencl'), ('Oz', 'oz'), ('Parigp', 'parigp'), ('Parser', 'parser'), ('Pascal', 'pascal'), ('Perl', 'perl'), ('PHP', 'php'), ('PowerShell', 'powershell'), ('Processing', 'processing'), ('Prolog', 'prolog'), ('Puppet', 'puppet'), ('Pure', 'pure'), ('Python', 'python'), ('Q', 'q'), ('Qore', 'qore'), ('R', 'r'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('Reason', 'reason'), ('Ruby', 'ruby'), ('Rust', 'rust'), ('SAS', 'sas'), ('Sass (Sass)', 'sass'), ('Sass (SCSS)', 'scss'), ('Scala', 'scala'), ('Scheme', 'scheme'), ('Shell', 'shell'), ('Smalltalk', 'smalltalk'), ('Smarty', 'smarty'), ('Solidity', 'solidity'), ('Soy (Closure Template)', 'soy'), ('SQL', 'sql'), ('Stylus', 'stylus'), ('Swift', 'swift'), ('Tcl', 'tcl'), ('Textile', 'textile'), ('Twig', 'twig'), ('TypeScript', 'typescript'), ('V', 'v'), ('VB.Net', 'vbnet'), ('Velocity', 'velocity'), ('Verilog', 'verilog'), ('VHDL', 'vhdl'), ('Vim', 'vim'), ('Visual Basic', 'visualbasic'), ('Wasm', 'wasm'), ('Wiki markup', 'wiki'), ('Xeora', 'xeora'), ('Xojo', 'xojo'), ('XQuery', 'xquery'), ('YAML', 'yaml')], default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
